version: "3"
services:
  mssql:
    image: mcr.microsoft.com/mssql/server
    restart: always
    container_name: mssql
    ports:
      - 1433:1433
    volumes:
      - /data/mssql/:/var/opt/mssql/data
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=123456
