version: "3"
services:
  mysql:
    image: mysql
    restart: always
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - /data/mysql/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
