version: "3"
services:
  meilisearch:
    image: getmeili/meilisearch
    restart: always
    container_name: meilisearch
    ports:
      - 7700:7700
    environment:
      MEILI_MASTER_KEY: ""
    volumes:
      - /data/meilisearch/data:/meili_data
